USE [master]
GO
/****** Object:  Database [case_teste_api]    Script Date: 16/08/2024 08:06:00 ******/
CREATE DATABASE [case_teste_api]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'case_teste_api', FILENAME = N'C:\Documentos\CodeGit\Case_Teste_API\database\case_teste_api.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'case_teste_api_log', FILENAME = N'C:\Documentos\CodeGit\Case_Teste_API\database\case_teste_api_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [case_teste_api] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [case_teste_api].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [case_teste_api] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [case_teste_api] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [case_teste_api] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [case_teste_api] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [case_teste_api] SET ARITHABORT OFF 
GO
ALTER DATABASE [case_teste_api] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [case_teste_api] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [case_teste_api] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [case_teste_api] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [case_teste_api] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [case_teste_api] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [case_teste_api] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [case_teste_api] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [case_teste_api] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [case_teste_api] SET  DISABLE_BROKER 
GO
ALTER DATABASE [case_teste_api] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [case_teste_api] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [case_teste_api] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [case_teste_api] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [case_teste_api] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [case_teste_api] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [case_teste_api] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [case_teste_api] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [case_teste_api] SET  MULTI_USER 
GO
ALTER DATABASE [case_teste_api] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [case_teste_api] SET DB_CHAINING OFF 
GO
ALTER DATABASE [case_teste_api] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [case_teste_api] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [case_teste_api] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [case_teste_api] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [case_teste_api] SET QUERY_STORE = OFF
GO
USE [case_teste_api]
GO
/****** Object:  Table [dbo].[Pessoa]    Script Date: 16/08/2024 08:06:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pessoa](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](100) NULL,
	[DataNascimento] [date] NULL,
	[ValorRenda] [decimal](18, 2) NULL,
	[CPF] [varchar](11) NULL,
 CONSTRAINT [PK_Pessoa] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Pessoa] ON 
GO
INSERT [dbo].[Pessoa] ([Id], [Nome], [DataNascimento], [ValorRenda], [CPF]) VALUES (1, N'JOSE PEDRO ANDRADE', CAST(N'2024-08-15' AS Date), CAST(2500.20 AS Decimal(18, 2)), N'00011122233')
GO
INSERT [dbo].[Pessoa] ([Id], [Nome], [DataNascimento], [ValorRenda], [CPF]) VALUES (2, N'MARIA DA SILVA SANTOS', CAST(N'1990-10-25' AS Date), CAST(1250.20 AS Decimal(18, 2)), N'10011122233')
GO
INSERT [dbo].[Pessoa] ([Id], [Nome], [DataNascimento], [ValorRenda], [CPF]) VALUES (3, N'JOSE CARLOS JUNIOR', CAST(N'1980-12-05' AS Date), CAST(850.00 AS Decimal(18, 2)), N'10011122222')
GO
SET IDENTITY_INSERT [dbo].[Pessoa] OFF
GO
USE [master]
GO
ALTER DATABASE [case_teste_api] SET  READ_WRITE 
GO
